server:
  port: 7010

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/wallpaper
    username: root
    password: kkkzoz
    driver-class-name: org.postgresql.Driver
    platform: POSTGRESQL
  redis:
    database: 0
    host: localhost
    port: 6380
    password:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      server-addr: http://localhost:8848
    stream:
      binders: #需要绑定的rabbitmq的服务信息
        defaultRabbit: #定义的名称，用于bidding整合
          type: rabbit  #消息组件类型
          environment: #配置rabbimq连接环境
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: root
                password: kkkzoz
                virtual-host: /      #虚拟路径
      bindings: #服务的整合处理
        saveOrderInput: #生产者绑定，这个是消息通道的名称---> 保存订单输入通道
          destination: exchange-saveOrder
          content-type: application/json
          default-binder: defaultRabbit
          group: saveOrderGroup
  mail:
    host: smtp.163.com
    username: kkkzoz@163.com
    password: NBESYBSJZVDULEJE
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
